# Generated by Django 2.1.3 on 2018-11-08 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('anio', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('numero_puertas', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('precio', models.CharField(max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
